baseURL = "https://spksteel.github.io"
languageCode = "en-us"
title = "SPK"
theme = "hyde"
publishdir = ".git/modules/spksteel.github.io/"
[Menus]
	main = [
		{Name = "Contact Us", URL = "https://spksteel.github.io/about/contact-us.md"}
	]

[params]
	description = "Steel fabrication business, family owned and operated for over 10 years."
